Controllers/TrainDaysController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineRailway;

namespace OnlineRailway.Controllers
{
    public class TrainDaysController : Controller
    {
        private RailwayEntities db = new RailwayEntities();

        // GET: TrainDays
        public ActionResult Index()
        {
            var trainDays = db.TrainDays.Include(t => t.TrainName);
            return View(trainDays.ToList());
        }

        // GET: TrainDays/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainDay trainDay = db.TrainDays.Find(id);
            if (trainDay == null)
            {
                return HttpNotFound();
            }
            return View(trainDay);
        }

        // GET: TrainDays/Create
        public ActionResult Create()
        {
            ViewBag.trainNameID = new SelectList(db.TrainNames, "id", "trainName1");
            return View();
        }

        // POST: TrainDays/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,trainNameID,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday")] TrainDay trainDay)
        {
            if (ModelState.IsValid)
            {
                db.TrainDays.Add(trainDay);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.trainNameID = new SelectList(db.TrainNames, "id", "trainName1", trainDay.trainNameID);
            return View(trainDay);
        }

        // GET: TrainDays/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainDay trainDay = db.TrainDays.Find(id);
            if (trainDay == null)
            {
                return HttpNotFound();
            }
            ViewBag.trainNameID = new SelectList(db.TrainNames, "id", "trainName1", trainDay.trainNameID);
            return View(trainDay);
        }

        // POST: TrainDays/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,trainNameID,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday")] TrainDay trainDay)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trainDay).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.trainNameID = new SelectList(db.TrainNames, "id", "trainName1", trainDay.trainNameID);
            return View(trainDay);
        }

        // GET: TrainDays/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainDay trainDay = db.TrainDays.Find(id);
            if (trainDay == null)
            {
                return HttpNotFound();
            }
            return View(trainDay);
        }

        // POST: TrainDays/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TrainDay trainDay = db.TrainDays.Find(id);
            db.TrainDays.Remove(trainDay);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/TrainNamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineRailway;

namespace OnlineRailway.Controllers
{
    public class TrainNamesController : Controller
    {
        private RailwayEntities db = new RailwayEntities();

        // GET: TrainNames
        public ActionResult Index()
        {
            return View(db.TrainNames.ToList());
        }

        // GET: TrainNames/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainName trainName = db.TrainNames.Find(id);
            if (trainName == null)
            {
                return HttpNotFound();
            }
            return View(trainName);
        }

        // GET: TrainNames/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TrainNames/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,trainName1")] TrainName trainName)
        {
            if (ModelState.IsValid)
            {
                db.TrainNames.Add(trainName);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(trainName);
        }

        // GET: TrainNames/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainName trainName = db.TrainNames.Find(id);
            if (trainName == null)
            {
                return HttpNotFound();
            }
            return View(trainName);
        }

        // POST: TrainNames/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,trainName1")] TrainName trainName)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trainName).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(trainName);
        }

        // GET: TrainNames/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainName trainName = db.TrainNames.Find(id);
            if (trainName == null)
            {
                return HttpNotFound();
            }
            return View(trainName);
        }

        // POST: TrainNames/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TrainName trainName = db.TrainNames.Find(id);
            db.TrainNames.Remove(trainName);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/TrainNames/Create.cshtml
@model OnlineRailway.TrainName

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>TrainName</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.trainName1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.trainName1, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.trainName1, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


<script src="/Backend/vendor/jquery/jquery.min.js"></script>
    <script src="/Backend/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="/Backend/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="/Backend/js/sb-admin-2.min.js"></script>

Views/TrainNames/Delete.cshtml
@model OnlineRailway.TrainName

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TrainName</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.trainName1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.trainName1)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>


<script src="/Backend/vendor/jquery/jquery.min.js"></script>
<script src="/Backend/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="/Backend/vendor/jquery-easing/jquery.easing.min.js"></script>
<!-- Custom scripts for all pages-->
<script src="/Backend/js/sb-admin-2.min.js"></script>

Views/TrainNames/Details.cshtml
@model OnlineRailway.TrainName

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>TrainName</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id)
        </dd>

    </dl>
    <dl class="dl-horizontal">
        <dt>
            @*@Html.DisplayNameFor(model => model.trainName1)*@
            Train Name
        </dt>

        <dd>
            @{
                string trainName = Model.trainName1.ToUpper();
            }
            @trainName
        </dd>

    </dl>
    <dl class="dl-horizontal">
        <dt>
            Departure Days
        </dt>

        <dd>
            @{
                string days = "";
                if (Model.TrainDays.Any(i => i.Monday == true)) { days += "Mon "; }
                if (Model.TrainDays.Any(i => i.Tuesday == true)) { days += "Tue "; }
                if (Model.TrainDays.Any(i => i.Wednesday == true)) { days += "Wed "; }
                if (Model.TrainDays.Any(i => i.Thursday == true)) { days += "Thu "; }
                if (Model.TrainDays.Any(i => i.Friday == true)) { days += "Fri "; }
                if (Model.TrainDays.Any(i => i.Saturday == true)) { days += "Sat "; }
                if (Model.TrainDays.Any(i => i.Sunday == true)) { days += "Sun "; }
            }
            @days
        </dd>

    </dl>
    <dl class="dl-horizontal">
        <dt>
            @*@Html.DisplayNameFor(model => model.trainName1)*@
            Train Route
        </dt>

        <dd>
            @{
                var routeName = Model.TrainRoutes.First(r => r.name != null);
            }
            @routeName.name.ToUpper();
        </dd>

    </dl>
    <dl class="dl-horizontal">
        <dt>
            Timings
        </dt>

        <dd>
            @{
                var train = Model.TrainTimeTables.First(t => t.upDepartureTime != null);
                var upDepTime = train.upDepartureTime;
                var upArrTime = train.upArrivalTime;
                var downDepTime = train.downDepartureTime;
                var downArrTime = train.downArrivalTime;
            }
            <table class="table">
                <tr style="text-align: center">
                    <th colspan="2">Up</th>
                    <th colspan="2">Down</th>
                </tr>
                <tr>
                    <td>Departure</td>
                    <td>Arrival</td>
                    <td>Departure</td>
                    <td>Arrival</td>
                </tr>
                <tr>
                    <td>@upDepTime</td>
                    <td>@upArrTime</td>
                    <td>@downDepTime</td>
                    <td>@downArrTime</td>
                </tr>
            </table>
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<script src="/Backend/vendor/jquery/jquery.min.js"></script>
<script src="/Backend/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="/Backend/vendor/jquery-easing/jquery.easing.min.js"></script>
<!-- Custom scripts for all pages-->
<script src="/Backend/js/sb-admin-2.min.js"></script>

Views/TrainNames/Edit.cshtml
@model OnlineRailway.TrainName

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>TrainName</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)

    <div class="form-group">
        <h4>Train Name</h4>
        @*@Html.LabelFor(model => model.trainName1, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            @Html.EditorFor(model => model.trainName1, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.trainName1, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.ActionLink("Edit Days", "Edit", "TrainDays", new { id = Model.TrainDays.First().id}, null) | 
    @Html.ActionLink("Edit Timings", "Edit", "TrainTimeTables ", new { id = Model.TrainTimeTables.First().id }, null)

    @*<div class="form-group">
            <h4>Train Days</h4>
            <div class="row">
                @{
                    var days = Model.TrainDays.First();
                }

                <div class="form-group row">
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(model => days.Monday.Value)
                            @Html.ValidationMessageFor(model => days.Monday, "", new { @class = "text-danger" })
                            @Html.LabelFor(model => days.Monday, htmlAttributes: new { @class = "control-label col-md-2" })
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(model => days.Tuesday.Value)
                            @Html.ValidationMessageFor(model => days.Tuesday, "", new { @class = "text-danger" })
                            @Html.LabelFor(model => days.Tuesday, htmlAttributes: new { @class = "control-label col-md-2" })
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(model => days.Wednesday.Value)
                            @Html.ValidationMessageFor(model => days.Wednesday, "", new { @class = "text-danger" })
                            @Html.LabelFor(model => days.Wednesday, htmlAttributes: new { @class = "control-label col-md-2" })
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(model => days.Thursday.Value)
                            @Html.ValidationMessageFor(model => days.Thursday, "", new { @class = "text-danger" })
                            @Html.LabelFor(model => days.Thursday, htmlAttributes: new { @class = "control-label col-md-2" })
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(model => days.Friday.Value)
                            @Html.ValidationMessageFor(model => days.Friday, "", new { @class = "text-danger" })
                            @Html.LabelFor(model => days.Friday, htmlAttributes: new { @class = "control-label col-md-2" })
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(model => days.Saturday.Value)
                            @Html.ValidationMessageFor(model => days.Saturday, "", new { @class = "text-danger" })
                            @Html.LabelFor(model => days.Saturday, htmlAttributes: new { @class = "control-label col-md-2" })
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(model => days.Sunday.Value)
                            @Html.ValidationMessageFor(model => days.Sunday, "", new { @class = "text-danger" })
                            @Html.LabelFor(model => days.Sunday, htmlAttributes: new { @class = "control-label col-md-2" })
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(model => days.Monday.Value)
                            @Html.ValidationMessageFor(model => days.Sunday, "", new { @class = "text-danger" })
                            @Html.LabelFor(model => days.Sunday, htmlAttributes: new { @class = "control-label col-md-2" })
                        </div>
                    </div>
                </div>
            </div>
        </div>*@

    @*<div class="form-group">
            <h4>Timings</h4>
            <div class="form-group">
                @Html.LabelFor(model => model.TrainTimeTables.First().upDepartureTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TrainTimeTables.First().upDepartureTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TrainTimeTables.First().upDepartureTime, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TrainTimeTables.First().upArrivalTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TrainTimeTables.First().upArrivalTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TrainTimeTables.First().upArrivalTime, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TrainTimeTables.First().downDepartureTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TrainTimeTables.First().downDepartureTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TrainTimeTables.First().downDepartureTime, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TrainTimeTables.First().downArrivalTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TrainTimeTables.First().downArrivalTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TrainTimeTables.First().downArrivalTime, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


<script src="/Backend/vendor/jquery/jquery.min.js"></script>
<script src="/Backend/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="/Backend/vendor/jquery-easing/jquery.easing.min.js"></script>
<!-- Custom scripts for all pages-->
<script src="/Backend/js/sb-admin-2.min.js"></script>

Views/TrainNames/Index.cshtml
@model IEnumerable<OnlineRailway.TrainName>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.trainName1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TrainDays)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TrainRoutes)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.trainName1)
            </td>
            @{
                string days = "";
                if (item.TrainDays.Any(i => i.Monday == true)) { days += "Mon "; }
                if (item.TrainDays.Any(i => i.Tuesday == true)) { days += "Tue "; }
                if (item.TrainDays.Any(i => i.Wednesday == true)) { days += "Wed "; }
                if (item.TrainDays.Any(i => i.Thursday == true)) { days += "Thu "; }
                if (item.TrainDays.Any(i => i.Friday == true)) { days += "Fri "; }
                if (item.TrainDays.Any(i => i.Saturday == true)) { days += "Sat "; }
                if (item.TrainDays.Any(i => i.Sunday == true)) { days += "Sun "; }
            }
            <td>
                @days
            </td>
            <td>
                @{
                    var routeName = item.TrainRoutes.FirstOrDefault(i => i.name != null);
                }
                @if (routeName != null)
                {
                    @routeName.name
                }
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>


<!-- Bootstrap core JavaScript-->
<script src="/Backend/vendor/jquery/jquery.min.js"></script>
<script src="/Backend/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="/Backend/vendor/jquery-easing/jquery.easing.min.js"></script>
<!-- Custom scripts for all pages-->
<script src="/Backend/js/sb-admin-2.min.js"></script>