Controllers/RouteStationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineRailway;

namespace OnlineRailway.Controllers
{
    public class RouteStationsController : Controller
    {
        private RailwayEntities db = new RailwayEntities();

        // GET: RouteStations
        public ActionResult Index()
        {
            var routeStations = db.RouteStations.Include(r => r.TrainRoute).Include(r => r.Station);
            return View(routeStations.ToList());
        }

        // GET: RouteStations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RouteStation routeStation = db.RouteStations.Find(id);
            if (routeStation == null)
            {
                return HttpNotFound();
            }
            return View(routeStation);
        }

        // GET: RouteStations/Create
        public ActionResult Create()
        {
            ViewBag.TrainRoutesID = new SelectList(db.TrainRoutes, "id", "name");
            ViewBag.StationID = new SelectList(db.Stations, "stationCode", "stationName");
            return View();
        }

        // POST: RouteStations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,TrainRoutesID,StationID,stationArrivalTime,stationDepartureTime,lastStationDistance,nextStationDistance")] RouteStation routeStation)
        {
            if (ModelState.IsValid)
            {
                db.RouteStations.Add(routeStation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TrainRoutesID = new SelectList(db.TrainRoutes, "id", "name", routeStation.TrainRoutesID);
            ViewBag.StationID = new SelectList(db.Stations, "stationCode", "stationName", routeStation.StationID);
            return View(routeStation);
        }

        // GET: RouteStations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RouteStation routeStation = db.RouteStations.Find(id);
            if (routeStation == null)
            {
                return HttpNotFound();
            }
            ViewBag.TrainRoutesID = new SelectList(db.TrainRoutes, "id", "name", routeStation.TrainRoutesID);
            ViewBag.StationID = new SelectList(db.Stations, "stationCode", "stationName", routeStation.StationID);
            return View(routeStation);
        }

        // POST: RouteStations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,TrainRoutesID,StationID,stationArrivalTime,stationDepartureTime,lastStationDistance,nextStationDistance")] RouteStation routeStation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(routeStation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TrainRoutesID = new SelectList(db.TrainRoutes, "id", "name", routeStation.TrainRoutesID);
            ViewBag.StationID = new SelectList(db.Stations, "stationCode", "stationName", routeStation.StationID);
            return View(routeStation);
        }

        // GET: RouteStations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RouteStation routeStation = db.RouteStations.Find(id);
            if (routeStation == null)
            {
                return HttpNotFound();
            }
            return View(routeStation);
        }

        // POST: RouteStations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RouteStation routeStation = db.RouteStations.Find(id);
            db.RouteStations.Remove(routeStation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/TrainRoutesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineRailway;

namespace OnlineRailway.Controllers
{
    public class TrainRoutesController : Controller
    {
        private RailwayEntities db = new RailwayEntities();

        // GET: TrainRoutes
        public ActionResult Index()
        {
            var trainRoutes = db.TrainRoutes.Include(t => t.TrainName);
            return View(trainRoutes.ToList());
        }

        // GET: TrainRoutes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainRoute trainRoute = db.TrainRoutes.Find(id);
            if (trainRoute == null)
            {
                return HttpNotFound();
            }
            ViewBag.routeStations = trainRoute.RouteStations.ToList();
            return View(trainRoute);
        }

        // GET: TrainRoutes/Create
        public ActionResult Create()
        {
            ViewBag.trainNameID = new SelectList(db.TrainNames, "id", "trainName1");
            return View();
        }

        // POST: TrainRoutes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,trainNameID,upOrDownStatus")] TrainRoute trainRoute)
        {
            if (ModelState.IsValid)
            {
                db.TrainRoutes.Add(trainRoute);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.trainNameID = new SelectList(db.TrainNames, "id", "trainName1", trainRoute.trainNameID);
            return View(trainRoute);
        }

        // GET: TrainRoutes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainRoute trainRoute = db.TrainRoutes.Find(id);
            if (trainRoute == null)
            {
                return HttpNotFound();
            }
            ViewBag.trainNameID = new SelectList(db.TrainNames, "id", "trainName1", trainRoute.trainNameID);
            return View(trainRoute);
        }

        // POST: TrainRoutes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,trainNameID,upOrDownStatus")] TrainRoute trainRoute)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trainRoute).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.trainNameID = new SelectList(db.TrainNames, "id", "trainName1", trainRoute.trainNameID);
            return View(trainRoute);
        }

        // GET: TrainRoutes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainRoute trainRoute = db.TrainRoutes.Find(id);
            if (trainRoute == null)
            {
                return HttpNotFound();
            }
            return View(trainRoute);
        }

        // POST: TrainRoutes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TrainRoute trainRoute = db.TrainRoutes.Find(id);
            db.TrainRoutes.Remove(trainRoute);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/TrainRoutes/Create.cshtml
@model OnlineRailway.TrainRoute

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TrainRoute</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.trainNameID, "trainNameID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("trainNameID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.trainNameID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.upOrDownStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.upOrDownStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.upOrDownStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>



<script src="/Backend/vendor/jquery/jquery.min.js"></script>
<script src="/Backend/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="/Backend/vendor/jquery-easing/jquery.easing.min.js"></script>
<!-- Custom scripts for all pages-->
<script src="/Backend/js/sb-admin-2.min.js"></script>

Views/TrainRoutes/Delete.cshtml
@model OnlineRailway.TrainRoute

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TrainRoute</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.upOrDownStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.upOrDownStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrainName.trainName1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrainName.trainName1)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>



<script src="/Backend/vendor/jquery/jquery.min.js"></script>
<script src="/Backend/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="/Backend/vendor/jquery-easing/jquery.easing.min.js"></script>
<!-- Custom scripts for all pages-->
<script src="/Backend/js/sb-admin-2.min.js"></script>

Views/TrainRoutes/Details.cshtml
@model OnlineRailway.TrainRoute

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/AdminLayout.cshtml";

    List<RouteStation> details = ViewBag.routeStations;
}

<h2>Details</h2>

<div>
    <h4>TrainRoute</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.upOrDownStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.upOrDownStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrainName.trainName1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrainName.trainName1)
        </dd>
    </dl>
</div>

<div class="card-body">
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Station</th>
                    <th>Arrival</th>
                    <th>Departure</th>
                    <th>Last Station Distance</th>
                    <th>Next Station Distance</th>
                    <th>Edit/Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in details)
                {
                    <tr>
                        <td>@item.Station.stationName</td>
                        <td>@item.stationArrivalTime</td>
                        <td>@item.stationDepartureTime</td>
                        <td>@item.lastStationDistance</td>
                        <td>@item.nextStationDistance</td>
                        <td>@Html.ActionLink("Edit", "Edit", "RouteStations", new { id = item.id }, null) | @Html.ActionLink("Delete", "Delete", "RouteStations", new { id = item.id }, null)</td>
                    </tr>
                }
                <tr>
                    <td colspan="6">@Html.ActionLink("Add New", "Create", "RouteStations")</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<p>     
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>



<script src="/Backend/vendor/jquery/jquery.min.js"></script>
<script src="/Backend/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="/Backend/vendor/jquery-easing/jquery.easing.min.js"></script>
<!-- Custom scripts for all pages-->
<script src="/Backend/js/sb-admin-2.min.js"></script>

Views/TrainRoutes/Edit.cshtml
@model OnlineRailway.TrainRoute

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TrainRoute</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.trainNameID, "trainNameID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("trainNameID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.trainNameID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.upOrDownStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.upOrDownStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.upOrDownStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index") |
    @Html.ActionLink("Edit Route Stations", "Details", new { id = Model.id })
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>





<script src="/Backend/vendor/jquery/jquery.min.js"></script>
<script src="/Backend/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="/Backend/vendor/jquery-easing/jquery.easing.min.js"></script>
<!-- Custom scripts for all pages-->
<script src="/Backend/js/sb-admin-2.min.js"></script>

Views/TrainRoutes/Index.cshtml
@model IEnumerable<OnlineRailway.TrainRoute>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.upOrDownStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TrainName.trainName1)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.upOrDownStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TrainName.trainName1)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>



<script src="/Backend/vendor/jquery/jquery.min.js"></script>
<script src="/Backend/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="/Backend/vendor/jquery-easing/jquery.easing.min.js"></script>
<!-- Custom scripts for all pages-->
<script src="/Backend/js/sb-admin-2.min.js"></script>